language: python
python:
- 3.6
install:
- pip install pytest pytest-mock
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: vivarium
  password:
    secure: SWxZ2CM61CD3u02wAIeatam7DL2phRX9o2U1D9bvOx61JPk7rg8cEmYe7OFP3rVa5TqmFsdWNVkxUEXFWfb5rNR77RNIpXWajjzosOmwO9NjAoF9ZcsBsNFIELTxmCdfkIAIRSarRh5n++lGFyTm7fFD+vLVMOLdhszl0javTgIjU/71f1rNNGbgM//xXf6wH2r4lk3V5krokFOD2oExHUzIsLSu0FkxLu/WPSRjGqKe2BqLd9ItUckDaWjI3L6KWcRSusxaiw2LUS7g8Qn8WyX3EwKqszt4e/Gk+GAiw6KU4CnC10YbeoahPZTeWWUMhld90wtmVj09NmP5z8lgrItVi7f6e/Ahn4TDoOlu1ZPPAp1vhyX7MjjgwJFx/rFrAiP9cwrhgIktU9TvfZyWczE9ElJ3miHZsliyNOi+4uwVCLDVMGhoMmCLOYidwgL+ZJCaRexHaOWIWEO/y1bJ3wUTdPuNxsc4UxFtk18CmzBshAVZPo67TJfgnU8RYTVRXoC1yoajtPUgSKXi3Bc7RtMwqzU4M5opGti6GOiQEi9hfhV9g5upmqTdRl6lO0qbnI3JOthUxgTmd6EOeOFqjaoXtU6PEIVsZ1fRTXrdLaluL5J42LHTJ06R56AjTlb2mPM1swCllZxrVCcK1pZOdMTsGomOI6rpvR+oqcCsWXo=
  on:
    distributions: sdist bdist_wheel
    repo: ihmeuw/risk_distributions
    tags: true
